### ISSUE TITLE
Elements in term table header overlap on mobile

### ISSUE THREAD

**Issue by wfdd** [everypolitician/viewer-sinatra#10131]
The download button sits on top of the search box, which sits on top of the 'Members' heading.

**Comment by tmtmtmtm** [comment]
Screenshot: 

![screen shot 2016-05-31 at 12 53 30](https://cloud.githubusercontent.com/assets/57483/15672096/c3189236-272e-11e6-80c7-9315c611b159.png)

**Comment by tmtmtmtm** [comment]
over to @zarino …

**Comment by zarino** [comment]
Yes, this is one of the few corners of EP that isn't responsive to small screens. (It used to be that very few EP.org users were on small screens, but now it's approaching 20%, so maybe worth spending a little time fixing the responsive styling bug like this.)

The fix in this case, is to make the three elements stack vertically when there isn't enough space.

There are a bunch of related tickets about how the ep-card-filters are presented, so when we're prioritising them, we should make sure not to duplicate / waste effort fixing things more than once:

* https://github.com/everypolitician/viewer-sinatra/issues/5408 – Keeping the filters in view when you scroll down the page (even more important on mobile, since the page will be 3 times taller!)
* https://github.com/everypolitician/viewer-sinatra/issues/6273 – Making dataset "facet" buttons (eg: "Biographical" vs "Social") more obvious.
* https://github.com/everypolitician/viewer-sinatra/pull/5349 – Making it more obvious when filters are in action.

**Comment by wfdd** [comment]
I thought I'd fix this but prefixing all the flex things by hand is a time sink.  Have you considered using something like [autoprefixer](https://github.com/postcss/autoprefixer) or even a version of [Bourbon](https://github.com/thoughtbot/bourbon) from before they dropped the prefixers?

**Comment by zarino** [comment]
Super simple pull request here: https://github.com/everypolitician/viewer-sinatra/pull/13802
