### ISSUE TITLE
Multiple same-person memberships without an end/start date count towards seat total

### ISSUE THREAD

**Issue by wfdd** [everypolitician/viewer-sinatra#14284]
[Per Rosing-Petersen](http://everypolitician.org/greenland/inatsisartut/term-table/12.html), for example, occupies two seats at the same time, with two different 'parties'.  Not sure what the best way to work around this is - maybe display the seat count for the two parties as a range, or use a different term for 'seats', or simply revert to showing all memberships for the legislative period?

**Comment by tmtmtmtm** [comment]
I'm a little confused as to what's happening here… Is the issue that he actually _does_ hold two seats at the same time, or that our data for this is wrong? I'm assuming it's the latter, but I'm not sure in what way. Is this just that he changed party at some point, and we have both those memberships appearing simultaneously?

**Comment by wfdd** [comment]
Yes, he left Partii Naleraq probably sometime in the last month.  The scraper keys the combination of name, term and party membership as unique and that's cascaded through to EP.org.  The issue is that the site shows him as holding two seats at the same time though he doesn't really.

**Comment by tmtmtmtm** [comment]
I think that simply clearing out the scraper's database and re-running should clear that up. 

It's not ideal, in that it's lossy, and we'll no longer know he was ever in Partii Naleraq, other than by trawling back through git history, but that's a trade-off we've accepted (for now) in quite a few other places too, and is better than the current version.

As a slight aside: in the medium-term we're hopefully solving this by migrating all the scrapers to build an archive of the pages they scrape as they go, using https://github.com/everypolitician/scraped_page_archive, so we can later time-travel in the parsing, if needed.

That's not immediately useful to you as you're using python, but we have longer term plans there too…

**Comment by wfdd** [comment]
> I think that simply clearing out the scraper's database and re-running should clear that up.

Well, yes, I was hoping not to resort to that ;)  It's a presentational issue, so - in theory - I shouldn't have to tamper with the data.  Anyway, I'll clear the database then.

> As a slight aside ...

I did something similar with the Bahamas scraper, albeit a lot less sophisticated.  A Python version would be awesome - or perhaps a language-agnostic/web API?

**Comment by tmtmtmtm** [comment]
>  It's a presentational issue

I'm not sure that it is. We're presenting exactly what the data claims — i.e. that the person held two simultaneous memberships (which can happen — the first few Irish Dáils had several people holding multiple seats). The data should ideally have an `end_date` on the membership on behalf of the first party, and a `start_date` on the membership on behalf of the second party. 

> A Python version would be awesome

It's still all a bit too experimental to port at this point, but part of what we're doing here is decoupling the fetching and the parsing. So, for example, we've started adding "scrapers" that simply visit the pages we want, and don't do any further processing yet, simply to start building that archive, and enable us to come back later and do the actual parsing, without fear that information will have been lost in the meantime. Any script that does that parsing then only needs to know how to convert from an upstream URL to, say, a rawgit one, to fetch from the archive rather than the live site. So _that_ script could much more easily be in python, or any other language, in the meantime, if some other fairly trivial ruby script has already visited and archived all the relevant pages…

**Comment by wfdd** [comment]
> We're presenting exactly what the data claims

While assuming an injective relationship between party memberships and party seats ... which would've been perfectly reasonable to assume if we could differentiate between a boundless membership and a membership with an unknown start and/or end date.  Presentation-wise, if the party-grouping table had simply said Partii Naleraq has three 'memberships', that'd probably be passably ambiguous.  (It'd be just nonsense to most people, but regardless.)

> It's still all a bit too experimental ...

That sounds like a great idea, though it'd probably be a little difficult to adapt to JS-heavy websites?  That is, scraping from the archive vs. scraping from the live site would be a little more involved than simply substituting part of the URL.

**Comment by tmtmtmtm** [comment]
> While assuming an injective relationship between party memberships and party seats

We very explicitly don't track party memberships at all. The only thing we track is legislative memberships on behalf of a party. So in some ways, yes, we're assuming that the Membership information means holding a seat, but it's not really just an _assumption_ as much as a foundational principle. It does mean, as you say, that we can't cope very well with vagueness around dates, but that was a deliberate design decision that arose out of our experience with PopIt and Pombola. If you allow those be vague, you end up with information that is of very little value in many cases, and makes lots of things that should be trivial almost impossible. 

Basically, we have no way for source data to tell us "This person was a member at some unknown time". I see that as a feature, not a bug :)

> probably be a little difficult to adapt to JS-heavy websites? (Or anything with forms/POST requests for that matter

Yes. We're not trying to solve every case. Even 90% would be easily good enough here, but I suspect it's actually going to be closer to 95%. Most official websites aren't that complex for the sort of data we need. Even with JS-driven sites, it's often enough to load the page, do the click-dance, and then archive off the current state of the HTML for later processing (or re-processing. If you discover later that the way you were extracting some field wasn't quite right, or even that a small subset of people had an extra field that you hadn't noticed, you shouldn't need to rescrape the site again, just reprocess against the archive).

**Comment by wfdd** [comment]
Scrubbing the data didn't fix it 'cause he's listed as representing Partii Naleraq in prior sessions of the current term.  What I _could_ do is use the date of each successive session as the end and start date of memberships within the last term, unless you've any better ideas.

**Comment by tmtmtmtm** [comment]
Do you have a simple reminder of the way the sessions/terms work? IIRC the dates on the Members page on inatsisartut.gl represent something different from a new term starting - are those based on a new Naalakkersuisut? 

And the issue here is that someone was listed as one party at one of those slice points within the current term, and a different one in another? If so, then yep, setting the dates based on those seems like the best approach we have at the minute.

**Comment by wfdd** [comment]
> IIRC the dates on the Members page on inatsisartut.gl represent something different from a new term starting - are those based on a new Naalakkersuisut?

Yep, to the best of my knowledge, that's how it works.  The date dropdown's labelled 'Konstitueringsdato', which apparently translates to 'appointment date' (the executive is appointed by Inatsisartut).

> ... setting the dates based on those seems like the best approach we have at the minute,

Alright, I'll go ahead with that.

**Comment by wfdd** [comment]
Accidentally deleted the scraper on Morph.io in the process, but this should be now fixed...
