### ISSUE TITLE
Better text for the "No data for this country" page

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#360]
https://github.com/everypolitician/viewer-sinatra/pull/359 added a very basic "Sorry, no data yet" page for countries which we currently have no data. This should include, or link to, much more information on how to help.

**Comment by zarino** [comment]
Currently looks like:

![screen shot 2015-07-09 at 12 28 13](https://cloud.githubusercontent.com/assets/739624/8594139/08565f40-2636-11e5-97b3-8859a43c70c4.png)

As well as providing more information about how to upload data, it's worth pointing out the [new `WORLD` array an app.rb](https://github.com/everypolitician/viewer-sinatra/blob/24b48f27ec4c6882f2bd741234f080f994ffd39c/app.rb#L18-L19) will contain the country's displayName, so we should be able to use that in the page text rather than the vague "that country".

**Comment by tmtmtmtm** [comment]
Yep — when I built this all I had was the slug from the URL, and trying to turn that back into something suitable for display was producing weird results. Now that we have this file, #380 takes care of only showing this page for slugs that are actually in `world.json` (anything else will 404), and displaying the country name.

We still need better text, though…

**Comment by tmtmtmtm** [comment]
We now link to the contributing page, which is a good enough first step.
