### ISSUE TITLE
It's not obvious that you can click the dataset sections

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/viewer-sinatra#6273]
The four items in the "What’s in this dataset?" section on a term page (e.g. http://everypolitician.org/finland/eduskunta/term-table/37.html) aren't obviously clickable.

![screen shot 2016-03-31 at 13 54 04](https://cloud.githubusercontent.com/assets/22996/14174944/2be35722-f748-11e5-98de-21565887e966.png)

**Comment by zarino** [comment]
@chrismytton: Are there always going to be 4 sections, or are there likely to be more over time?

**Comment by chrismytton** [comment]
@zarino There will likely be more over time.

**Comment by zarino** [comment]
The “what’s in this dataset?” element currently performs two functions:

1. It shows what types of data we hold about politicians in this term, and roughly how "complete" that data is.
2. It lets you toggle what type of data is visible in the cards further down the page.

It performs the first function fairly well. But the "click to toggle" affordance isn't obvious enough, most likely because:

1. The things you’re meant to click don’t look like buttons or interactive form elements. The pie charts in particular make them look like static, informational elements, not interactive toggles.
2. The toggles are physically a long way from the cards they affect – so far that, on short screens, you often can't see both the controls and the cards at the same time.
3. The toggles don't look or behave like any of the other controls on the page.

Things we could try to solve this:

1. Make the toggles look more clickable – style them as buttons, or form elements, that people know they can click.
2. Move the toggles closer to the cards they affect.
3. Style the toggles consistently with other interactive elements on the page.

So, I'm currently considering a layout like this, where we have one consistent style and location for all of the controls that modify the grid of people, including the "Show details" toggle:

![desktop](https://cloud.githubusercontent.com/assets/739624/17292524/946cbb1c-57e2-11e6-887f-c5071d4d1c55.png)

And on narrow screens:

![mobile](https://cloud.githubusercontent.com/assets/739624/17292529/a0061d2e-57e2-11e6-8910-ce1fcdd0d98e.png)

As shown in #5408, the controls could dock to the top of the window when you scroll, making it easier to switch the visible card sections without having to scroll back to the top of the list each time.

We could keep the percentage breakdown in the “what’s in this dataset” section – with or without the current (hidden) clickable functionality.
