### ISSUE TITLE
Add a predicable URL for the latest country data

### ISSUE THREAD

**Issue by henare** [everypolitician/viewer-sinatra#707]
Sorry if this is the wrong repo. It would be great if there was a predicable URL for the latest country data - even if it just redirected to the latest version of the data for that country.

**Comment by tmtmtmtm** [comment]
Hi @henare 

> Sorry if this is the wrong repo

Yeah — it's not always easy to know where to open tickets. I tend to fall back on https://github.com/everypolitician/everypolitician/issues as the catch-all, when it's not clear.  

> It would be great if there was a predicable URL for the latest country data

Can you explain a little more what you mean by that? Are you talking about raw data? If so, then you can just point at master on github: e.g. https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/data/Ukraine/Verkhovna_Rada/ep-popolo-v1.0.json

That's not absolutely guaranteed to be consistent (we could rename the legislature for example), but if you're looking for a 99% solution, it'll be good enough. Looking it up in `countries.json` is safer, though an extra step (though, as a bonus, it also gives you the SHA of the last commit if you need to use rawgit.com instead of githubusercontent.com, e.g. to get correct headers)

**Comment by henare** [comment]
>Yeah — it's not always easy to know where to open tickets. I tend to fall back on https://github.com/everypolitician/everypolitician/issues as the catch-all, when it's not clear. 

Thanks - I'm all to familiar with this problem with my own repos! :smile: 

>Can you explain a little more what you mean by that? Are you talking about raw data? If so, then you can just point at master on github: e.g. https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/data/Ukraine/Verkhovna_Rada/ep-popolo-v1.0.json

Sweet - that works for me!

**Comment by henare** [comment]
@tmtmtmtm thanks very much for getting back to me so quickly with the solution :bouquet:
