### ISSUE TITLE
Tidy the 'countries' page

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#721]
http://everypolitician.org/countries.html

Now that we have almost every country that is actually visible on the map, we should rethink whether it makes as much sense any more (or if we should more prominently highlight the ones we're missing, possibly combining it with [/needed.html](http://everypolitician.org/countries.html) in some way?)

Is a massive columned list the best way to display the countries now that there are more than 200 of them?

Should this page also have the search box that's on the home page? 

Should it even exist at all?

**Comment by zarino** [comment]
I think the countries page is still useful, but as you say, it needs some changes now that it's matured.

Off the top of my head:

* Change the map so that it highlights missing countries more strongly. Use the EP salmon colour perhaps? Need to check whether that sits well with green for existing countries, or whether the existing countries need to be scaled back to grey.
* Combining this page with http://everypolitician.org/needed seems sensible. Especially since the map will now be more clearly showing both.
* To combat the "gigantic list of countries" effect, maybe split them into continents?
* I'm not convinced the little people in circles is adding anything to such a long list – feels a bit like noise to me. Maybe try without the circles? All the country names could also easily be a bit smaller, and no longer bold, to reduce some of the plonky weight.

**Comment by tmtmtmtm** [comment]
I'm open to all sorts of options on this, though I'm a little worried by the geo-politicial minefield edge-cases involved in splitting into continents…

**Comment by zarino** [comment]
@tmtmtmtm Have you come across any less minefieldy ways of splitting up a list of countries, because I'm drawing a blank.

I guess you could split them into little alphabetical groups, so all the "A" countries, then all the "B" countries, etc. At least then you could quickly scan down to where you guess your country might be.

**Comment by tmtmtmtm** [comment]
Grouping by first letter is probably OK. Maybe we should add the filter box from the homepage here again too?

**Comment by tmtmtmtm** [comment]
Closed by #770
